-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 09:25:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS DEFAULT CHARACTER SET utf8 ;
USE ;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `usuid` INT NOT NULL AUTO_INCREMENT,
  `usuemail` VARCHAR(100) NOT NULL,
  `ususenha` VARCHAR(100) NOT NULL,
  `usutelefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`usuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores` (
  `venid` INT NOT NULL AUTO_INCREMENT,
  `usuid` INT NOT NULL,
  `vennome` VARCHAR(45) NULL,
  PRIMARY KEY (`venid`),
  INDEX `fk_vendedores_usuarios_idx` (`usuid` ASC) ,
  CONSTRAINT `fk_vendedores_usuarios`
    FOREIGN KEY (`usuid`)
    REFERENCES `usuarios` (`usuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enderecos` (
  `endid` INT NOT NULL AUTO_INCREMENT,
  `usuid` INT NOT NULL,
  `endcep` VARCHAR(8) NULL,
  `enduf` VARCHAR(2) NULL,
  `endcidade` VARCHAR(100) NULL,
  `endbairro` VARCHAR(50) NULL,
  `endrua` VARCHAR(45) NULL,
  `endnumero` INT NULL,
  `endnome` VARCHAR(45) NULL,
  PRIMARY KEY (`endid`),
  INDEX `fk_enderecos_usuarios1_idx` (`usuid` ASC) ,
  CONSTRAINT `fk_enderecos_usuarios1`
    FOREIGN KEY (`usuid`)
    REFERENCES `usuarios` (`usuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojas` (
  `lojid` INT NOT NULL AUTO_INCREMENT,
  `usuid` INT(11) NOT NULL,
  `venid` INT NOT NULL,
  `lojnomeempresa` VARCHAR(100) NULL,
  `lojcpf` VARCHAR(11) NULL,
  `lojcnpj` VARCHAR(14) NULL,
  `lojtelefone` VARCHAR(11) NULL,
  PRIMARY KEY (`lojid`),
  INDEX `fk_lojas_vendedores1_idx` (`venid` ASC) ,
  INDEX `fk_lojas_usuarios1_idx` (`usuid` ASC) ,
  CONSTRAINT `fk_lojas_vendedores1`
    FOREIGN KEY (`venid`)
    REFERENCES `vendedores` (`venid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lojas_usuarios1`
    FOREIGN KEY (`usuid`)
    REFERENCES `usuarios` (`usuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categorias_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categorias_produtos` (
  `catprodid` INT NOT NULL AUTO_INCREMENT,
  `usuid` INT NOT NULL,
  `lojid` INT NOT NULL,
  `catprodnome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`catprodid`),
  INDEX `fk_categorias_produtos_lojas1_idx` (`lojid` ASC) ,
  INDEX `fk_categorias_produtos_usuarios1_idx` (`usuid` ASC) ,
  CONSTRAINT `fk_categorias_produtos_lojas1`
    FOREIGN KEY (`lojid`)
    REFERENCES `lojas` (`lojid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_produtos_usuarios1`
    FOREIGN KEY (`usuid`)
    REFERENCES `usuarios` (`usuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos` (
  `prodid` INT NOT NULL AUTO_INCREMENT,
  `usuid` INT NOT NULL,
  `lojid` INT NOT NULL,
  `catprodid` INT NOT NULL,
  `prodnome` VARCHAR(50) NOT NULL,
  `proddescricao` VARCHAR(100) NOT NULL,
  `prodvalor` DECIMAL(10,2) NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`prodid`),
  INDEX `fk_produtos_lojas1_idx` (`lojid` ASC) ,
  INDEX `fk_produtos_categorias_produtos1_idx` (`catprodid` ASC) ,
  INDEX `fk_produtos_usuarios1_idx` (`usuid` ASC) ,
  CONSTRAINT `fk_produtos_lojas1`
    FOREIGN KEY (`lojid`)
    REFERENCES `lojas` (`lojid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_categorias_produtos1`
    FOREIGN KEY (`catprodid`)
    REFERENCES `categorias_produtos` (`catprodid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_usuarios1`
    FOREIGN KEY (`usuid`)
    REFERENCES `usuarios` (`usuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `design`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `design` (
  `desid` INT NOT NULL AUTO_INCREMENT,
  `usuid` INT NOT NULL,
  `lojid` INT NOT NULL,
  `desnome` VARCHAR(100) NOT NULL,
  `descorpadrao` VARCHAR(20) NOT NULL,
  `descorsecundaria` VARCHAR(20) NOT NULL,
  `deslogo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`desid`),
  INDEX `fk_design_lojas1_idx` (`lojid` ASC) ,
  INDEX `fk_design_usuarios1_idx` (`usuid` ASC) ,
  CONSTRAINT `fk_design_lojas1`
    FOREIGN KEY (`lojid`)
    REFERENCES `lojas` (`lojid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_design_usuarios1`
    FOREIGN KEY (`usuid`)
    REFERENCES `usuarios` (`usuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `promocoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promocoes` (
  `promoid` INT NOT NULL AUTO_INCREMENT,
  `usuid` INT NOT NULL,
  `lojid` INT NOT NULL,
  `promonome` VARCHAR(100) NOT NULL,
  `promodescricao` VARCHAR(250) NOT NULL,
  `promovalortotal` DECIMAL(10,2) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`promoid`),
  INDEX `fk_promocoes_lojas1_idx` (`lojid` ASC) ,
  INDEX `fk_promocoes_usuarios1_idx` (`usuid` ASC) ,
  CONSTRAINT `fk_promocoes_lojas1`
    FOREIGN KEY (`lojid`)
    REFERENCES `lojas` (`lojid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promocoes_usuarios1`
    FOREIGN KEY (`usuid`)
    REFERENCES `usuarios` (`usuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `combo` (
  `comid` INT NOT NULL AUTO_INCREMENT,
  `promoid` INT NOT NULL,
  `prodid` INT NOT NULL,
  `comqtde` INT NOT NULL,
  PRIMARY KEY (`comid`, `promoid`, `prodid`),
  INDEX `fk_promocoes_has_produtos_produtos1_idx` (`prodid` ASC) ,
  INDEX `fk_promocoes_has_produtos_promocoes1_idx` (`promoid` ASC) ,
  CONSTRAINT `fk_promocoes_has_produtos_promocoes1`
    FOREIGN KEY (`promoid`)
    REFERENCES `promocoes` (`promoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promocoes_has_produtos_produtos1`
    FOREIGN KEY (`prodid`)
    REFERENCES `produtos` (`prodid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acrescimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acrescimo` (
  `acrid` INT NOT NULL AUTO_INCREMENT,
  `lojid` INT NOT NULL,
  `catprodid` INT NOT NULL,
  `usuid` INT NOT NULL,
  `acrnome` VARCHAR(100) NOT NULL,
  `acrvalor` DECIMAL(10,2) NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`acrid`),
  INDEX `fk_acrescimo_lojas1_idx` (`lojid` ASC) ,
  INDEX `fk_acrescimo_categorias_produtos1_idx` (`catprodid` ASC) ,
  INDEX `fk_acrescimo_usuarios1_idx` (`usuid` ASC) ,
  CONSTRAINT `fk_acrescimo_lojas1`
    FOREIGN KEY (`lojid`)
    REFERENCES `lojas` (`lojid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acrescimo_categorias_produtos1`
    FOREIGN KEY (`catprodid`)
    REFERENCES `categorias_produtos` (`catprodid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acrescimo_usuarios1`
    FOREIGN KEY (`usuid`)
    REFERENCES `usuarios` (`usuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imagens_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imagens_produtos` (
  `imgproid` INT NOT NULL,
  `prodid` INT NOT NULL,
  `imgprocaminho` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`imgproid`),
  INDEX `fk_imagens_produtos_produtos1_idx` (`prodid` ASC) ,
  CONSTRAINT `fk_imagens_produtos_produtos1`
    FOREIGN KEY (`prodid`)
    REFERENCES `produtos` (`prodid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imagens_promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imagens_promocao` (
  `imgpromoid` INT NOT NULL AUTO_INCREMENT,
  `promoid` INT NOT NULL,
  `imgpromocaminho` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`imgpromoid`),
  INDEX `fk_imagens_promocao_promocoes1_idx` (`promoid` ASC) ,
  CONSTRAINT `fk_imagens_promocao_promocoes1`
    FOREIGN KEY (`promoid`)
    REFERENCES `promocoes` (`promoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
